# Generated by Django 6.0.6 on 2026-07-07 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_lostfound_notice_studymaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='posted_on',
        ),
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('exam', 'Exam'), ('general', 'General')], default='academic', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
