# Generated by Django 6.0.6 on 2026-07-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_notice_posted_on_notice_category_notice_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Main Campus', max_length=200),
            preserve_default=False,
        ),
    ]
