# Generated by Django 6.0.6 on 2026-07-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_event_date_event_date_event_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='title',
            field=models.CharField(default='untitled material', max_length=200),
            preserve_default=False,
        ),
    ]
