# Generated by Django 6.0.6 on 2026-07-07 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_studymaterial_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostfound',
            name='contact',
        ),
        migrations.AddField(
            model_name='lostfound',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostfound',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lostfound',
            name='location',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lostfound',
            name='status',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10),
        ),
    ]
