# Generated by Django 6.0.6 on 2026-07-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_lostfound_contact_lostfound_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('exam', 'Exam'), ('holiday', 'Holiday'), ('semester', 'Semester')], max_length=20)),
                ('image', models.URLField(blank=True)),
            ],
        ),
    ]
